# Generated by Django 3.1.7 on 2021-05-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_auto_20210510_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
