# Generated by Django 3.1.7 on 2021-05-11 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_auto_20210510_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.item'),
        ),
    ]
