# Generated by Django 3.1.7 on 2021-05-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0005_auto_20210512_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ShopItem',
        ),
    ]
