# Generated by Django 3.1.7 on 2021-05-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0007_auto_20210515_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='item',
            new_name='clothing',
        ),
    ]
