# Generated by Django 3.1.7 on 2021-05-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0009_auto_20210519_0641'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='sampleapp_item',
        ),
    ]
