# Generated by Django 3.1.7 on 2021-05-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0011_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
