# Generated by Django 3.1.7 on 2021-05-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0010_auto_20210523_2332'),
        ('sampleapp', '0012_delete_search'),
    ]

    operations = [
    ]
