# Generated by Django 3.1.7 on 2021-05-26 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0013_merge_20210526_0527'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Size',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_type',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='type',
            new_name='size',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.size'),
        ),
    ]
