# Generated by Django 3.1.7 on 2021-05-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0019_auto_20210526_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.purchasechoices')),
            ],
        ),
    ]
