# Generated by Django 3.1.7 on 2021-05-31 22:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0021_auto_20210528_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2040)])),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.IntegerField(null=True)),
                ('cardpin', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)])),
                ('cardday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.day')),
                ('cardmonth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.month')),
                ('cardyear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.year')),
            ],
        ),
    ]
