# Generated by Django 3.1.7 on 2021-06-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0029_auto_20210603_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='cardday',
        ),
    ]
