# Generated by Django 3.1.7 on 2021-06-21 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0030_remove_creditcard_cardday'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(null=True, verbose_name=django.core.validators.MinValueValidator(0)),
        ),
    ]
