# Generated by Django 3.1.7 on 2021-06-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0031_item_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
